title: Super Awesome Title
author: dafuego1
email: diegodlrosa1234@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  xd
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dafuego1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
